// @generated by scripts/generate-qa-catalog.mjs from rayfin/connectors/c360lakehouse. Do not edit by hand.
/** A column the in-app Q&A may read. */
export interface QaColumn { name: string; type: 'string' | 'number' | 'date' | 'boolean' }
/** A gold table the in-app Q&A may read (entity = connector entity name). */
export interface QaTable { entity: string; table: string; description: string; columns: QaColumn[] }

export const QA_CATALOG: readonly QaTable[] = [
  {
    "entity": "GoldCustomerCascade",
    "table": "gold_customer_cascade",
    "description": "Customers with a support spike: spike month, engagement and monthly sales before/after, months until disengagement / sales decline, and pattern.",
    "columns": [
      {
        "name": "unifiedCustomerId",
        "type": "string"
      },
      {
        "name": "customerType",
        "type": "string"
      },
      {
        "name": "customerName",
        "type": "string"
      },
      {
        "name": "region",
        "type": "string"
      },
      {
        "name": "accountManager",
        "type": "string"
      },
      {
        "name": "spikeMonth",
        "type": "date"
      },
      {
        "name": "ticketsInSpikeMonth",
        "type": "number"
      },
      {
        "name": "engagementBefore",
        "type": "number"
      },
      {
        "name": "engagementAfter",
        "type": "number"
      },
      {
        "name": "monthlySalesBefore",
        "type": "number"
      },
      {
        "name": "monthlySalesAfter",
        "type": "number"
      },
      {
        "name": "engagementDropLag",
        "type": "number"
      },
      {
        "name": "salesDropLag",
        "type": "number"
      },
      {
        "name": "pattern",
        "type": "string"
      }
    ]
  },
  {
    "entity": "GoldCustomerMetrics",
    "table": "gold_customer_metrics",
    "description": "One row per Wholesale/Direct customer: last-12-month (TTM) and prior-year sales, YoY, returns, product lines bought, tickets, marketing engagement, churnRiskScore (0-100) with band and drivers (JSON), upsell score and value, revenueAtRisk, nextBestAction.",
    "columns": [
      {
        "name": "unifiedCustomerId",
        "type": "string"
      },
      {
        "name": "customerType",
        "type": "string"
      },
      {
        "name": "customerName",
        "type": "string"
      },
      {
        "name": "region",
        "type": "string"
      },
      {
        "name": "accountManager",
        "type": "string"
      },
      {
        "name": "isProMember",
        "type": "boolean"
      },
      {
        "name": "netSalesTtm",
        "type": "number"
      },
      {
        "name": "netSalesPriorTtm",
        "type": "number"
      },
      {
        "name": "salesYoy",
        "type": "number"
      },
      {
        "name": "ordersTtm",
        "type": "number"
      },
      {
        "name": "lastOrderDate",
        "type": "date"
      },
      {
        "name": "daysSinceOrder",
        "type": "number"
      },
      {
        "name": "returnsTtm",
        "type": "number"
      },
      {
        "name": "returnRateTtm",
        "type": "number"
      },
      {
        "name": "defectReturnsTtm",
        "type": "number"
      },
      {
        "name": "productLinesTtm",
        "type": "number"
      },
      {
        "name": "tickets12m",
        "type": "number"
      },
      {
        "name": "tickets90d",
        "type": "number"
      },
      {
        "name": "openTickets",
        "type": "number"
      },
      {
        "name": "highPriorityOpen",
        "type": "number"
      },
      {
        "name": "badCsat12m",
        "type": "number"
      },
      {
        "name": "avgResolutionMinutes12m",
        "type": "number"
      },
      {
        "name": "touches90d",
        "type": "number"
      },
      {
        "name": "engagements90d",
        "type": "number"
      },
      {
        "name": "engagementRate90d",
        "type": "number"
      },
      {
        "name": "engagementRatePrior",
        "type": "number"
      },
      {
        "name": "daysSinceEngaged",
        "type": "number"
      },
      {
        "name": "churnRiskScore",
        "type": "number"
      },
      {
        "name": "churnRiskBand",
        "type": "string"
      },
      {
        "name": "topChurnDriver",
        "type": "string"
      },
      {
        "name": "churnDrivers",
        "type": "string"
      },
      {
        "name": "upsellScore",
        "type": "number"
      },
      {
        "name": "upsellValueEst",
        "type": "number"
      },
      {
        "name": "topUpsellProductLine",
        "type": "string"
      },
      {
        "name": "revenueAtRisk",
        "type": "number"
      },
      {
        "name": "priorityScore",
        "type": "number"
      },
      {
        "name": "nextBestAction",
        "type": "string"
      },
      {
        "name": "asOfDate",
        "type": "date"
      },
      {
        "name": "city",
        "type": "string"
      },
      {
        "name": "state",
        "type": "string"
      },
      {
        "name": "lifecycleStage",
        "type": "string"
      },
      {
        "name": "latitude",
        "type": "number"
      },
      {
        "name": "longitude",
        "type": "number"
      },
      {
        "name": "productLinesBought",
        "type": "string"
      }
    ]
  },
  {
    "entity": "GoldCustomerMonthly",
    "table": "gold_customer_monthly",
    "description": "Customer x month: net sales, orders, returns, Klaviyo touches/engagements, Zendesk tickets, plus customerType/region/accountManager.",
    "columns": [
      {
        "name": "unifiedCustomerId",
        "type": "string"
      },
      {
        "name": "customerType",
        "type": "string"
      },
      {
        "name": "region",
        "type": "string"
      },
      {
        "name": "accountManager",
        "type": "string"
      },
      {
        "name": "state",
        "type": "string"
      },
      {
        "name": "city",
        "type": "string"
      },
      {
        "name": "churnRiskBand",
        "type": "string"
      },
      {
        "name": "lifecycleStage",
        "type": "string"
      },
      {
        "name": "isProMember",
        "type": "boolean"
      },
      {
        "name": "productLinesBought",
        "type": "string"
      },
      {
        "name": "month",
        "type": "date"
      },
      {
        "name": "netSales",
        "type": "number"
      },
      {
        "name": "orders",
        "type": "number"
      },
      {
        "name": "returnsAmount",
        "type": "number"
      },
      {
        "name": "returnsCount",
        "type": "number"
      },
      {
        "name": "marketingTouches",
        "type": "number"
      },
      {
        "name": "marketingEngagements",
        "type": "number"
      },
      {
        "name": "tickets",
        "type": "number"
      }
    ]
  },
  {
    "entity": "GoldCustomerProductLine",
    "table": "gold_customer_product_line",
    "description": "Customer x product line: TTM sales, share of the customer's sales, purchased flag, product views in 90 days, peer penetration.",
    "columns": [
      {
        "name": "unifiedCustomerId",
        "type": "string"
      },
      {
        "name": "productLine",
        "type": "string"
      },
      {
        "name": "netSalesTtm",
        "type": "number"
      },
      {
        "name": "shareOfSalesTtm",
        "type": "number"
      },
      {
        "name": "purchasedTtm",
        "type": "boolean"
      },
      {
        "name": "lastPurchased",
        "type": "date"
      },
      {
        "name": "views90d",
        "type": "number"
      },
      {
        "name": "peerPenetration",
        "type": "number"
      }
    ]
  },
  {
    "entity": "GoldCustomerSku",
    "table": "gold_customer_sku",
    "description": "Customer x SKU over 24 months: TTM and prior sales, units, returns, last purchase date.",
    "columns": [
      {
        "name": "unifiedCustomerId",
        "type": "string"
      },
      {
        "name": "customerType",
        "type": "string"
      },
      {
        "name": "customerName",
        "type": "string"
      },
      {
        "name": "region",
        "type": "string"
      },
      {
        "name": "accountManager",
        "type": "string"
      },
      {
        "name": "sku",
        "type": "string"
      },
      {
        "name": "productName",
        "type": "string"
      },
      {
        "name": "productLine",
        "type": "string"
      },
      {
        "name": "netSalesTtm",
        "type": "number"
      },
      {
        "name": "netSalesPriorTtm",
        "type": "number"
      },
      {
        "name": "returnsTtm",
        "type": "number"
      },
      {
        "name": "unitsTtm",
        "type": "number"
      },
      {
        "name": "lastPurchased",
        "type": "date"
      }
    ]
  },
  {
    "entity": "GoldCustomerSkuRecs",
    "table": "gold_customer_sku_recs",
    "description": "Top 5 recommended SKUs per customer with estimated annual value and reason.",
    "columns": [
      {
        "name": "unifiedCustomerId",
        "type": "string"
      },
      {
        "name": "rank",
        "type": "number"
      },
      {
        "name": "sku",
        "type": "string"
      },
      {
        "name": "productName",
        "type": "string"
      },
      {
        "name": "productLine",
        "type": "string"
      },
      {
        "name": "score",
        "type": "number"
      },
      {
        "name": "estimatedAnnualValue",
        "type": "number"
      },
      {
        "name": "becauseSku",
        "type": "string"
      },
      {
        "name": "reason",
        "type": "string"
      }
    ]
  },
  {
    "entity": "GoldCustomerTimeline",
    "table": "gold_customer_timeline",
    "description": "Latest 25 events per customer: orders, returns, marketing clicks, support tickets.",
    "columns": [
      {
        "name": "unifiedCustomerId",
        "type": "string"
      },
      {
        "name": "eventAt",
        "type": "date"
      },
      {
        "name": "source",
        "type": "string"
      },
      {
        "name": "title",
        "type": "string"
      },
      {
        "name": "detail",
        "type": "string"
      }
    ]
  },
  {
    "entity": "GoldCustomerUpsell",
    "table": "gold_customer_upsell",
    "description": "Top 3 product-line upsell recommendations per customer with estimated annual value and reason.",
    "columns": [
      {
        "name": "unifiedCustomerId",
        "type": "string"
      },
      {
        "name": "rank",
        "type": "number"
      },
      {
        "name": "productLine",
        "type": "string"
      },
      {
        "name": "estimatedAnnualValue",
        "type": "number"
      },
      {
        "name": "peerPenetration",
        "type": "number"
      },
      {
        "name": "views90d",
        "type": "number"
      },
      {
        "name": "reason",
        "type": "string"
      }
    ]
  },
  {
    "entity": "GoldDimCustomer",
    "table": "gold_dim_customer",
    "description": "One row per unified customer across ERP, Shopify, Klaviyo and Zendesk: type, name, region, owner, which systems they appear in, consent, lifecycle stage, active channels.",
    "columns": [
      {
        "name": "unifiedCustomerId",
        "type": "string"
      },
      {
        "name": "customerType",
        "type": "string"
      },
      {
        "name": "customerName",
        "type": "string"
      },
      {
        "name": "primaryEmail",
        "type": "string"
      },
      {
        "name": "city",
        "type": "string"
      },
      {
        "name": "state",
        "type": "string"
      },
      {
        "name": "region",
        "type": "string"
      },
      {
        "name": "accountManager",
        "type": "string"
      },
      {
        "name": "locationCount",
        "type": "number"
      },
      {
        "name": "paymentTerms",
        "type": "string"
      },
      {
        "name": "isProMember",
        "type": "boolean"
      },
      {
        "name": "customerSince",
        "type": "date"
      },
      {
        "name": "inErp",
        "type": "boolean"
      },
      {
        "name": "inShopify",
        "type": "boolean"
      },
      {
        "name": "inKlaviyo",
        "type": "boolean"
      },
      {
        "name": "inZendesk",
        "type": "boolean"
      },
      {
        "name": "sourceSystemCount",
        "type": "number"
      },
      {
        "name": "erpCustomerNumber",
        "type": "string"
      },
      {
        "name": "shopifyCustomerId",
        "type": "string"
      },
      {
        "name": "zendeskOrganizationId",
        "type": "string"
      },
      {
        "name": "klaviyoProfileCount",
        "type": "number"
      },
      {
        "name": "zendeskUserCount",
        "type": "number"
      },
      {
        "name": "linkedSourceRecords",
        "type": "number"
      },
      {
        "name": "identityConfidence",
        "type": "number"
      },
      {
        "name": "emailMarketingConsent",
        "type": "boolean"
      },
      {
        "name": "smsMarketingConsent",
        "type": "boolean"
      },
      {
        "name": "firstOrderDate",
        "type": "date"
      },
      {
        "name": "lastOrderDate",
        "type": "date"
      },
      {
        "name": "lifetimeOrders",
        "type": "number"
      },
      {
        "name": "orders12m",
        "type": "number"
      },
      {
        "name": "lastEmailEngagementAt",
        "type": "date"
      },
      {
        "name": "lastSmsClickAt",
        "type": "date"
      },
      {
        "name": "lastWebActivityAt",
        "type": "date"
      },
      {
        "name": "lastSupportContactAt",
        "type": "date"
      },
      {
        "name": "tickets12m",
        "type": "number"
      },
      {
        "name": "openTickets",
        "type": "number"
      },
      {
        "name": "activeChannels12m",
        "type": "string"
      },
      {
        "name": "activeChannelCount12m",
        "type": "number"
      },
      {
        "name": "lifecycleStage",
        "type": "string"
      },
      {
        "name": "asOfDate",
        "type": "date"
      }
    ]
  },
  {
    "entity": "GoldDriverCorrelation",
    "table": "gold_driver_correlation",
    "description": "Correlation of each risk driver (measured 6 months ago) with the sales change since, by customer type.",
    "columns": [
      {
        "name": "driverKey",
        "type": "string"
      },
      {
        "name": "driver",
        "type": "string"
      },
      {
        "name": "customerType",
        "type": "string"
      },
      {
        "name": "correlation",
        "type": "number"
      },
      {
        "name": "n",
        "type": "number"
      },
      {
        "name": "salesChangeWhenHigh",
        "type": "number"
      },
      {
        "name": "salesChangeOtherwise",
        "type": "number"
      },
      {
        "name": "highDefinition",
        "type": "string"
      }
    ]
  },
  {
    "entity": "GoldIdentityMergeCandidates",
    "table": "gold_identity_merge_candidates",
    "description": "Pairs of customers that are probably the same person, with evidence and a match score.",
    "columns": [
      {
        "name": "candidateId",
        "type": "string"
      },
      {
        "name": "primaryCustomerId",
        "type": "string"
      },
      {
        "name": "secondaryCustomerId",
        "type": "string"
      },
      {
        "name": "primaryCustomerType",
        "type": "string"
      },
      {
        "name": "secondaryCustomerType",
        "type": "string"
      },
      {
        "name": "primaryCustomerName",
        "type": "string"
      },
      {
        "name": "secondaryCustomerName",
        "type": "string"
      },
      {
        "name": "primaryPrimaryEmail",
        "type": "string"
      },
      {
        "name": "secondaryPrimaryEmail",
        "type": "string"
      },
      {
        "name": "primaryCity",
        "type": "string"
      },
      {
        "name": "secondaryCity",
        "type": "string"
      },
      {
        "name": "primaryState",
        "type": "string"
      },
      {
        "name": "secondaryState",
        "type": "string"
      },
      {
        "name": "primaryLifetimeOrders",
        "type": "number"
      },
      {
        "name": "secondaryLifetimeOrders",
        "type": "number"
      },
      {
        "name": "primarySourceSystemCount",
        "type": "number"
      },
      {
        "name": "secondarySourceSystemCount",
        "type": "number"
      },
      {
        "name": "score",
        "type": "number"
      },
      {
        "name": "handleSimilarity",
        "type": "number"
      },
      {
        "name": "sameCity",
        "type": "boolean"
      },
      {
        "name": "sameName",
        "type": "boolean"
      },
      {
        "name": "orderRefs",
        "type": "number"
      },
      {
        "name": "reasons",
        "type": "string"
      }
    ]
  },
  {
    "entity": "GoldIssueCascade",
    "table": "gold_issue_cascade",
    "description": "Event study by month relative to a support spike (relMonth -6..9): sales index vs. pre-spike baseline and marketing engagement rate, for \"Support spike\" vs. \"No spike\" cohorts.",
    "columns": [
      {
        "name": "cohort",
        "type": "string"
      },
      {
        "name": "customerType",
        "type": "string"
      },
      {
        "name": "relMonth",
        "type": "number"
      },
      {
        "name": "customers",
        "type": "number"
      },
      {
        "name": "salesIndex",
        "type": "number"
      },
      {
        "name": "engagementRate",
        "type": "number"
      },
      {
        "name": "ticketsPerCustomer",
        "type": "number"
      }
    ]
  },
  {
    "entity": "GoldProductLinePenetration",
    "table": "gold_product_line_penetration",
    "description": "Share of active customers (by customer type) who bought each product line, and average spend per buyer.",
    "columns": [
      {
        "name": "customerType",
        "type": "string"
      },
      {
        "name": "productLine",
        "type": "string"
      },
      {
        "name": "penetration",
        "type": "number"
      },
      {
        "name": "activeCustomers",
        "type": "number"
      },
      {
        "name": "avgSpendPerBuyer",
        "type": "number"
      }
    ]
  },
  {
    "entity": "GoldRiskConcentration",
    "table": "gold_risk_concentration",
    "description": "Revenue at risk by dimension (Region, Account owner, Product line, Risk band) and customer type.",
    "columns": [
      {
        "name": "dimension",
        "type": "string"
      },
      {
        "name": "value",
        "type": "string"
      },
      {
        "name": "customerType",
        "type": "string"
      },
      {
        "name": "customers",
        "type": "number"
      },
      {
        "name": "highRiskCustomers",
        "type": "number"
      },
      {
        "name": "netSalesTtm",
        "type": "number"
      },
      {
        "name": "revenueAtRisk",
        "type": "number"
      },
      {
        "name": "shareOfRisk",
        "type": "number"
      }
    ]
  },
  {
    "entity": "GoldSkuAffinity",
    "table": "gold_sku_affinity",
    "description": "SKU pairs bought by the same customers (\"bought together\"): confidence and lift, top 5 per SKU.",
    "columns": [
      {
        "name": "customerType",
        "type": "string"
      },
      {
        "name": "sku",
        "type": "string"
      },
      {
        "name": "rank",
        "type": "number"
      },
      {
        "name": "relatedSku",
        "type": "string"
      },
      {
        "name": "relatedProductName",
        "type": "string"
      },
      {
        "name": "relatedProductLine",
        "type": "string"
      },
      {
        "name": "pairCustomers",
        "type": "number"
      },
      {
        "name": "confidence",
        "type": "number"
      },
      {
        "name": "lift",
        "type": "number"
      }
    ]
  },
  {
    "entity": "GoldSkuPerformance",
    "table": "gold_sku_performance",
    "description": "SKU x customer type: TTM and prior sales, units, buyers, returns, defect returns, linked support tickets, return rate, YoY, repeat buyer rate.",
    "columns": [
      {
        "name": "sku",
        "type": "string"
      },
      {
        "name": "productName",
        "type": "string"
      },
      {
        "name": "productLine",
        "type": "string"
      },
      {
        "name": "category",
        "type": "string"
      },
      {
        "name": "customerType",
        "type": "string"
      },
      {
        "name": "netSalesTtm",
        "type": "number"
      },
      {
        "name": "netSalesPriorTtm",
        "type": "number"
      },
      {
        "name": "returnsTtm",
        "type": "number"
      },
      {
        "name": "defectReturnsTtm",
        "type": "number"
      },
      {
        "name": "unitsTtm",
        "type": "number"
      },
      {
        "name": "buyersTtm",
        "type": "number"
      },
      {
        "name": "ticketsLinkedTtm",
        "type": "number"
      },
      {
        "name": "returnRateTtm",
        "type": "number"
      },
      {
        "name": "salesYoy",
        "type": "number"
      },
      {
        "name": "repeatBuyerRate",
        "type": "number"
      }
    ]
  }
];
